// Theory Constants and Definitions for DNDPLHLS
// Generated by Lead Researcher Subagent

/**
 * Basic interface for a Just Intonation ratio
 */
export interface Ratio {
  n: number; // Numerator
  d: number; // Denominator
}

/**
 * Interface for a musical interval
 */
export interface Interval {
  name: string;
  ratio: Ratio;
  cents: number;
  limit: number; // Prime limit (e.g., 3, 5, 7)
}

/**
 * Interface for a comma definition
 */
export interface Comma {
  name: string;
  ratio: Ratio;
  cents: number;
  vector: number[]; // Prime vector [2, 3, 5, 7...]
  description: string;
}

/**
 * Interface for a parsed Scala file
 */
export interface SclFile {
  filename: string;
  description: string;
  count: number;
  lines: (string | number)[]; // Can be ratio string "3/2" or cent number 702.0
}

// ------------------------------------------------------------------
// Fundamental Commas
// ------------------------------------------------------------------

export const COMMAS: Comma[] = [
  {
    name: "Syntonic Comma",
    ratio: { n: 81, d: 80 },
    cents: 21.506,
    vector: [-4, 4, -1], // 2^-4 * 3^4 * 5^-1
    description: "The difference between four perfect fifths and two octaves plus a major third."
  },
  {
    name: "Pythagorean Comma",
    ratio: { n: 531441, d: 524288 },
    cents: 23.460,
    vector: [-19, 12], // 2^-19 * 3^12
    description: "The difference between twelve perfect fifths and seven octaves."
  },
  {
    name: "Diesis (Lesser)",
    ratio: { n: 128, d: 125 },
    cents: 41.059,
    vector: [7, 0, -3], // 2^7 * 5^-3
    description: "The difference between an octave and three major thirds."
  },
  {
    name: "Schisma",
    ratio: { n: 32805, d: 32768 },
    cents: 1.954,
    vector: [-15, 8, 1], // 2^-15 * 3^8 * 5^1
    description: "The difference between the Pythagorean comma and the Syntonic comma."
  },
  {
    name: "Kleisma",
    ratio: { n: 15625, d: 15552 },
    cents: 8.11,
    vector: [-6, -5, 6], // 2^-6 * 3^-5 * 5^6
    description: "The difference between six minor thirds and an octave + one fifth."
  },
  {
    name: "Septimal Comma (Archytas)",
    ratio: { n: 64, d: 63 },
    cents: 27.26,
    vector: [6, -2, 0, -1], // 2^6 * 3^-2 * 7^-1
    description: "The difference between the octave and the septimal sixth + perfect fourth."
  }
];

// ------------------------------------------------------------------
// Just Intonation Intervals
// ------------------------------------------------------------------

export const JI_INTERVALS: Interval[] = [
  // 3-Limit
  { name: "Unison", ratio: { n: 1, d: 1 }, cents: 0, limit: 1 },
  { name: "Perfect Fifth", ratio: { n: 3, d: 2 }, cents: 701.955, limit: 3 },
  { name: "Perfect Fourth", ratio: { n: 4, d: 3 }, cents: 498.045, limit: 3 },
  { name: "Major Whole Tone", ratio: { n: 9, d: 8 }, cents: 203.91, limit: 3 },
  { name: "Pythagorean Major Third", ratio: { n: 81, d: 64 }, cents: 407.82, limit: 3 },
  
  // 5-Limit
  { name: "Just Major Third", ratio: { n: 5, d: 4 }, cents: 386.314, limit: 5 },
  { name: "Just Minor Third", ratio: { n: 6, d: 5 }, cents: 315.641, limit: 5 },
  { name: "Just Major Sixth", ratio: { n: 5, d: 3 }, cents: 884.359, limit: 5 },
  { name: "Just Minor Sixth", ratio: { n: 8, d: 5 }, cents: 813.686, limit: 5 },
  { name: "Just Major Seventh", ratio: { n: 15, d: 8 }, cents: 1088.27, limit: 5 },
  { name: "Just Minor Second", ratio: { n: 16, d: 15 }, cents: 111.73, limit: 5 },

  // 7-Limit
  { name: "Harmonic Seventh", ratio: { n: 7, d: 4 }, cents: 968.826, limit: 7 },
  { name: "Septimal Major Second", ratio: { n: 8, d: 7 }, cents: 231.174, limit: 7 },
  { name: "Septimal Minor Third", ratio: { n: 7, d: 6 }, cents: 266.87, limit: 7 },
  { name: "Septimal Tritone", ratio: { n: 7, d: 5 }, cents: 582.51, limit: 7 },

  // 11-Limit & Higher
  { name: "Undecimal Neutral Second", ratio: { n: 11, d: 10 }, cents: 165.00, limit: 11 },
  { name: "Undecimal Neutral Third", ratio: { n: 11, d: 9 }, cents: 347.41, limit: 11 },
  { name: "Tridecimal Neutral Sixth", ratio: { n: 13, d: 8 }, cents: 840.53, limit: 13 }
];

// ------------------------------------------------------------------
// Analyzed SCL Files (Sample)
// ------------------------------------------------------------------

export const ANALYZED_SCL_FILES: SclFile[] = [
  {
    filename: "ji_12.scl",
    description: "Basic JI with 7-limit tritone. Robert Rich: Geometry",
    count: 12,
    lines: [
      "16/15", "9/8", "6/5", "5/4", "4/3", "7/5", "3/2", "8/5", "5/3", "9/5", "15/8", "2/1"
    ]
  },
  {
    filename: "slendro.scl",
    description: "Observed Javanese Slendro scale, Helmholtz/Ellis p. 518, nr.94",
    count: 5,
    lines: [
      228.00000, 484.00000, 728.00000, 960.00000, "2/1"
    ]
  },
  {
    filename: "young.scl",
    description: "Thomas Young well temperament (1807)",
    count: 12,
    lines: [
      "256/243", 196.09000, "32/27", 392.18000, "4/3", "1024/729", 698.04500, "128/81", 894.13500, "16/9", 1090.22500, "2/1"
    ]
  }
];

// ------------------------------------------------------------------
// Regular Temperament Mapping Matrices
// ------------------------------------------------------------------

/**
 * Mapping matrices for various regular temperaments.
 * Format: Rows correspond to generators (typically [Octave, Generator]),
 * Columns correspond to primes [2, 3, 5, 7, ...].
 */
export const TEMPERAMENT_MATRICES = {
  // Meantone (Rank 2)
  // Generator is the Fifth (~696.6 cents)
  // Primes: [2, 3, 5]
  MEANTONE: [
    [1, 0, -4], // Period: Octave (2/1) -> 1*1200 + 0*Gen - 4*Gen (Tempered out syntonic comma means 4 fifths = 1 major third + 2 octaves)
    // Wait, standard val notation is simpler. Let's use Val vectors.
  ],
  
  // Using Vals (steps per prime) for standard tunings
  // Val <12 19 28| means:
  // 2 -> 12 steps
  // 3 -> 19 steps
  // 5 -> 28 steps
  VALS: {
    // 12-TET (Meantone optimization)
    TET_12: [12, 19, 28, 34, 42, 44], // 2, 3, 5, 7, 11, 13
    
    // 19-TET (Meantone, better thirds)
    TET_19: [19, 30, 44, 53, 66, 70],
    
    // 31-TET (Meantone, very good thirds and sevenths)
    TET_31: [31, 49, 72, 87, 107, 115],
    
    // 22-TET (Porcupine)
    TET_22: [22, 35, 51, 62, 76, 81],
    
    // 53-TET (Schismatic / Pythagorean)
    TET_53: [53, 84, 123, 149, 183, 196]
  }
};
